insert into `fixedAsset`.`MOBILE` (`newId`,`deviceName`,`type`,`configure`,`price`,`purchaseDate`,`possessDate`,`lastUserId`,`purpose`,`remark`,`reject`,`rejectDate`) values ('105-0002','移动硬盘','','','','','','张亮','工程公用','','','');
insert into `fixedAsset`.`MOBILE` (`newId`,`deviceName`,`type`,`configure`,`price`,`purchaseDate`,`possessDate`,`lastUserId`,`purpose`,`remark`,`reject`,`rejectDate`) values ('105-0025','USB无线网卡','LINKSYS','WUSB 54','220','2009-02-06T00:00:00','','张世同','ERP公用','','','');
insert into `fixedAsset`.`MOBILE` (`newId`,`deviceName`,`type`,`configure`,`price`,`purchaseDate`,`possessDate`,`lastUserId`,`purpose`,`remark`,`reject`,`rejectDate`) values ('105-0026','无线路由器','LINKSYS','WRT 54G','410','2009-02-06T00:00:00','','付阶辉','ERP公用','','','');
insert into `fixedAsset`.`MOBILE` (`newId`,`deviceName`,`type`,`configure`,`price`,`purchaseDate`,`possessDate`,`lastUserId`,`purpose`,`remark`,`reject`,`rejectDate`) values ('105-0027','无线路由器','LINKSYS','WRT 54G','411','2009-02-06T00:00:00','','杜华明','CCS公用','','','');
insert into `fixedAsset`.`MOBILE` (`newId`,`deviceName`,`type`,`configure`,`price`,`purchaseDate`,`possessDate`,`lastUserId`,`purpose`,`remark`,`reject`,`rejectDate`) values ('105-1054','三星Android 手机','三星i9020 NexusS','','4800','2011-03-01T00:00:00','','顾卫永','','','','');
insert into `fixedAsset`.`MOBILE` (`newId`,`deviceName`,`type`,`configure`,`price`,`purchaseDate`,`possessDate`,`lastUserId`,`purpose`,`remark`,`reject`,`rejectDate`) values ('105-1055','3G联通数据卡（上网卡）','Iphone 用小卡','','960','2011-03-01T00:00:00','','顾卫永','','','','');
insert into `fixedAsset`.`MOBILE` (`newId`,`deviceName`,`type`,`configure`,`price`,`purchaseDate`,`possessDate`,`lastUserId`,`purpose`,`remark`,`reject`,`rejectDate`) values ('105-1056','Iphone4 16G 手机','苹果（Iphone4智能手机）','','6550','2011-03-02T00:00:00','','顾卫永','','','','');
insert into `fixedAsset`.`MOBILE` (`newId`,`deviceName`,`type`,`configure`,`price`,`purchaseDate`,`possessDate`,`lastUserId`,`purpose`,`remark`,`reject`,`rejectDate`) values ('105-1057','sony 录音笔','ICD-UX512F','2GB','1080','2011-03-14T00:00:00','','赵颖','','','','');
insert into `fixedAsset`.`MOBILE` (`newId`,`deviceName`,`type`,`configure`,`price`,`purchaseDate`,`possessDate`,`lastUserId`,`purpose`,`remark`,`reject`,`rejectDate`) values ('105-1058','无线网卡（3G上网卡（联通960）加设备）','','','1299','2011-03-28T00:00:00','','董霜','','','','');
